### ISSUE TITLE
Money reward

### ISSUE THREAD

**Issue by ScRumP479** [CritteRo/lslSpeedtrap#1]
Dear, 

Is there any way to add a reward like money to bank in this script? 

so everytime you get X speed X money.

If so that would be of great help, cant seem to adjust the code to make it work.

Thanks!

**Comment by CritteRo** [comment]
Heyo, you can use the server event to catch people, and add your own logic for money:

```lua
RegisterNetEvent("lslSpeedtrap.Got_A_Runner", function(_trapid, _speed)
-- source = the source id of the player that triggered the camera
-- _trapid = the camera id
-- _speed = the speed that the player had. (The number generated by GetPlayerSpeed() )
end)
```
You can add it in any resource. There is also this event handler in lslSpeedtraps > server. You should be able to modify that as well.

**Comment by ScRumP479** [comment]
Perfect, thanks for your help!
